### ISSUE TITLE
青龙面板按教程装好依赖，发现跑不起来，任务报错，不知道哪里出问题了

### ISSUE THREAD

**Issue by jackpater** [OreosLab/checkinpanel#147]
`吾爱破解
## 开始执行... 2022-08-18 07:59:23

/ql/data/config/config.sh: line 22: 1: command not found
# 当前总共 1 个 JD_COOKIE。

# 优先固定账号数量不得大于或等于有效账号总量，本次暂不重组 Cookie ...
尝试检查运行环境...
成功，当前环境为: 青龙面板(v2.12.0+)。
环境检查结束。

配置文件 (notify.toml) 检查开始...
在 /ql/data/config/notify.toml 发现配置文件。
配置文件检查结束。

通知配置文件存在：/ql/data/config/notify.toml。
Traceback (most recent call last):
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/ck_pojie.py", line 11, in <module>
    from utils import get_data
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/utils.py", line 9, in <module>
    from utils_ver import print_ver
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/utils_ver.py", line 8
    <<<<<<< HEAD
    ^
SyntaxError: invalid syntax`

**Comment by Oreomeow** [comment]
```bash
git fetch --all && git reset origin --hard origin/master
```

**Comment by Amongsterdevil** [comment]
我也完成了，但我来晚了，看下一个项目
