### ISSUE TITLE
smzdm ck error

### ISSUE THREAD

**Issue by cikichen** [OreosLab/checkinpanel#167]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/OreosLab_checkinpanel_master/ck_smzdm.py", line 93, in <module>
    send("什么值得买", result)
  File "/ql/data/scripts/OreosLab_checkinpanel_master/notify_mtr.py", line 610, in send
    content += "\n\n> " + one() if hitokoto else ""
                          ^^^^^
  File "/ql/data/scripts/OreosLab_checkinpanel_master/notify_mtr.py", line 549, in one
    res = requests.get(url).json()
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Oreomeow** [comment]
已修复
