### ISSUE TITLE
依赖安装出问题

### ISSUE THREAD

**Issue by Zynismus16** [OreosLab/checkinpanel#168]
按照教程上运行签到依赖文件
## 开始执行... 2022-11-09 15:10:41

```
fetch https://mirrors.aliyun.com/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
v3.16.2-427-gde115af66e [https://mirrors.aliyun.com/alpine/v3.16/main]
v3.16.2-428-g7c54fa7ef8 [https://mirrors.aliyun.com/alpine/v3.16/community]
OK: 17037 distinct packages available
bash 已安装
curl 已安装
.......... apk add gcc begin ..........
---------- apk add gcc succeed ----------
git 已安装
jq 已安装
.......... apk add libffi-dev begin ..........
---------- apk add libffi-dev succeed ----------
.......... apk add make begin ..........
---------- apk add make succeed ----------
.......... apk add musl-dev begin ..........
---------- apk add musl-dev succeed ----------
.......... apk add openssl-dev begin ..........
---------- apk add openssl-dev succeed ----------
perl 已安装
.......... apk add perl-app-cpanminus begin ..........
---------- apk add perl-app-cpanminus succeed ----------
.......... apk add perl-dev begin ..........
---------- apk add perl-dev succeed ----------
.......... apk add py3-pip begin ..........
---------- apk add py3-pip succeed ----------
.......... apk add python3 begin ..........
---------- apk add python3 succeed ----------
.......... apk add python3-dev begin ..........
---------- apk add python3-dev succeed ----------
wget 已安装
Looking in indexes: https://pypi.doubanio.com/simple/
Requirement already satisfied: pip in /usr/local/lib/python3.11/site-packages (22.3)
Collecting pip
  Downloading https://pypi.doubanio.com/packages/09/bd/2410905c76ee14c62baf69e3f4aa780226c1bbfc9485731ad018e35b0cb5/pip-22.3.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 13.4 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3
    Uninstalling pip-22.3:
      Successfully uninstalled pip-22.3
Successfully installed pip-22.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install bs4 begin ..........
---------- pip3 install bs4 succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install cryptography begin ..........
---------- pip3 install cryptography succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install dateparser begin ..........
---------- pip3 install dateparser succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install feedparser begin ..........
---------- pip3 install feedparser succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install peewee begin ..........
---------- pip3 install peewee succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install pyaes begin ..........
---------- pip3 install pyaes succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install pyppeteer begin ..........
---------- pip3 install pyppeteer succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install requests begin ..........
---------- pip3 install requests succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install rsa begin ..........
---------- pip3 install rsa succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install schedule begin ..........
---------- pip3 install schedule succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install tomli begin ..........
---------- pip3 install tomli succeed ----------

up to date in 811ms
@iarna/toml 已正确安装
axios 已正确安装
cron-parser 已正确安装
crypto-js 已正确安装
got 已正确安装
checkinpanel@4.0.0 /ql/data/scripts/OreosLab_checkinpanel_master
├── @iarna/toml@2.2.5
├── axios@0.23.0
├── cron-parser@4.6.0
├── crypto-js@4.1.1
├── got@11.8.5
└── request@2.88.2
```

执行到这一步后再无日志输出，但是任务却还在继续运行

![QQ截图20221109155555.png](https://img1.imgtp.com/2022/11/09/N9UwDsOi.png)

已提前运行过国内加速任务

环境

青龙docker 
版本v2.14.12

更新时间2022-11-05 16:43:28
更新ID5efc3d2

**Comment by Zynismus16** [comment]
运行签到任务报错
```
配置文件 (notify.toml) 检查开始...
在 /ql/data/config/notify.toml 发现配置文件。
配置文件检查结束。

通知配置文件存在：/ql/data/config/notify.toml。
checkinpanel 当前版本：20221108-4-010，不在 8-12 点内，跳过版本检查。

配置文件 (check.toml) 检查开始...
在 /ql/data/config/check.toml 发现配置文件。
配置文件检查结束。

Traceback (most recent call last):
  File "/ql/data/scripts/OreosLab_checkinpanel_master/ck_tieba.py", line 114, in <module>
    result = Tieba(check_items=_check_items).main()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/OreosLab_checkinpanel_master/ck_tieba.py", line 94, in main
    cookie = {
             ^
  File "/ql/data/scripts/OreosLab_checkinpanel_master/ck_tieba.py", line 95, in <dictcomp>
    item.split("=")[0]: item.split("=")[1]
                        ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by Zynismus16** [comment]
依赖安装大概两个小时后后面的日志出来了

```
checkinpanel@4.0.0 /ql/data/scripts/OreosLab_checkinpanel_master
├── @iarna/toml@2.2.5
├── axios@0.23.0
├── cron-parser@4.6.0
├── crypto-js@4.1.1
├── got@11.8.5
└── request@2.88.2

App::cpm 已安装
File::Slurp 已安装
JSON5 已安装
No documentation found for "TOML::Dumper".
FAIL install TOML-Dumper-0.01
0 distribution installed.
See /root/.perl-cpm/build.log for details.
You may want to execute cpm with --show-build-log-on-failure,
so that the build.log is automatically dumped on failure.
.......... cpm install -g TOML::Dumper begin ..........
---------- cpm install -g TOML::Dumper succeed ----------
```

**Comment by Zynismus16** [comment]
依赖安装问题已经通过手动安装解决，但是运行贴吧签到脚本还是报错

```
## 开始执行... 2022-11-09 19:40:38

Traceback (most recent call last):
  File "/ql/data/scripts/OreosLab_checkinpanel_master/ck_tieba.py", line 12, in <module>
    from notify_mtr import send
ModuleNotFoundError: No module named 'notify_mtr'
```

由于不是程序员专业，我尝试通过pip安装notify 后依旧报错

**Comment by night-raise** [comment]
notify 这个是项目中的文件，不是依赖包。
是不是拉库有问题?可以手动下载 notify_mtr.py 到对应目录。
